apiVersion: apps/v1
kind: Deployment
metadata:
  name: shoppingclient-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shoppingclient
  template:
    metadata:
      labels:
        app: shoppingclient
    spec:
      containers:
      - name: shoppingclient
        image: shiveshpandey05/shoppingclient:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Development
          - name: ShoppingAPIUrl
            valueFrom: 
              configMapKeyRef:
                name: shoppingapi-configmap
                key: shoppingapi_url
---
apiVersion: v1
kind: Service
metadata:
  name: shoppingclient-service
spec:
  type: NodePort
  selector:
    app: shoppingclient
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 80
      nodePort: 30000