version: '3.4'

services:
  shopping.api:
    image: shoppingapi:dev
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "Shopping.API"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_shopping.api$
    volumes:
      - C:\Users\spandey\source\repos\Microservices-K8-CICD\Shopping\Shopping.API:/app
      - C:\Users\spandey\source\repos\Microservices-K8-CICD\Shopping:/src
      - C:\Users\spandey\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_shopping.api$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_shopping.api$ \"/app/bin/Debug/net5.0/Shopping.API.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true
  shopping.client:
    image: shoppingclient:dev
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "Shopping.Client"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_shopping.client$
    volumes:
      - C:\Users\spandey\source\repos\Microservices-K8-CICD\Shopping\Shopping.Client:/app
      - C:\Users\spandey\source\repos\Microservices-K8-CICD\Shopping:/src
      - C:\Users\spandey\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_shopping.client$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_shopping.client$ \"/app/bin/Debug/net5.0/Shopping.Client.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true
